### get annotated cat image
POST http://127.0.0.1:8000/annotate
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat3.jpg"
Content-Type: image/jpeg

< data/cat10.jpg

--WebAppBoundary

### crop image of cats using landmarks

POST http://127.0.0.1:8000/crop
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat1.jpg"
Content-Type: image/jpeg

< data/cat1.jpg

--WebAppBoundary

> {% client.global.set("img_url", response.body.images[0]);%}

### get cropped image

GET {{img_url}}




### Align cat faces
POST http://127.0.0.1:8000/align_face
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat10.jpg"
Content-Type: image/jpeg

< data/cat10.jpg
--WebAppBoundary--

> {% client.global.set("img_url", response.body.images[0]);
  client.global.set("img_url_2", response.body.images[1]); %}



### show first aligned cat face
GET {{img_url}}

### show second aligned cat face
GET {{img_url_2}}
